name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk
          pip3 install cython buildozer
      
      - name: Build APK
        run: |
          buildozer init
          sed -i 's/android.api = 35/android.api = 30/' buildozer.spec
          sed -i 's/android.sdk = 35/android.sdk = 30/' buildozer.spec
          sed -i 's/# android.ndk = .*/android.ndk = 25b/' buildozer.spec
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          yes | buildozer android debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: snake-game
          path: bin/*.apk
